### ISSUE TITLE
Custom color variable position

### ISSUE THREAD

**Issue by hiulit** [philliprower/color-svg-icons#3]
It would be useful to be able to change the way the color variable names are appended to the `.svg`.
 For example to be able to append them ala BEM `--blue`.

Could be accomplished by adding options, something like this:

``` javascript
options: {
    prefix: '--' // Add whatever prefix the user wants.
    prepend: false // True by default and thus prepending the variables. When false, it appends them.
}
```

Just thinking :)

**Comment by hiulit** [comment]
Also, it would be useful too if we could assign a `default` and a `hover` color, something like this:

``` javascript
    options: {
        colors: {
            default: '#ccc'
            hover: '#ff0000'
        }
    }
```

And this would translate to `icon.svg` and `icon-hover.svg` and the CSS would be something like this:

``` css
.icon {
    width: 20px;
    height: 20px;
    background-position: 0 0;
}

.icon:hover {
    width: 20px;
    height: 20px;
    background-position: 0 -20px;
}
```
